title: Lightcodepedia
description: A GitHub Pages site

defaults:
  - scope:
      path: "modules"   # only /modules
    values:
      layout: null      # donâ€™t wrap them in HTML

# Important: tell Jekyll to copy .yaml as-is
include:
  - modules
  - modules/*.yaml

mermaid:
  # pick any version listed on jsDelivr
  version: "10.9.1"